### PR TITLE
CI on GitHub Actions

### LINKED ISSUE #68: CI
Hey! I noticed this repo isn't building on a CI in the cloud. Do you like any help on setting this up? (AppVeyor, it's free for OSS)

It's my way to say: thx :)

### PR DESCRIPTION
**Pull request by 304NotModified**
Fixes #68 

- I disabled creating the package on build, as it's confusing if it uses the incorrect parameters
- I converted the net472 project to SDK csproj style. Was needed for this. 

Maybe next step is to publish nuget packages from GitHub actions

### CODE REVIEW

**Comment by 304NotModified** [comment]
Demo here: https://github.com/304NotModified/RazorEngineCore/actions/runs/1085004202

**Comment by 304NotModified** [comment]
> Maybe next step is to publish nuget packages from GitHub actions

And drop pack.ps1

**Comment by 304NotModified** [comment]
polite bump @adoconnection

**Comment by adoconnection** [comment]
done!

**Pull request merged**
